- id: '1707927514356'
  alias: BMotion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion
      light_target:
        entity_id: light.bathroom
- id: '1707927634977'
  alias: Emotion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.entry_motion
      light_target:
        entity_id: light.entry
      no_motion_wait: 60
- id: '1707930534922'
  alias: Onward!
  description: ''
  trigger:
  - platform: time
    at: 06:15:00
    id: weekday
  - platform: time
    at: 08:00:00
    id: weekend
  - platform: state
    entity_id:
    - input_boolean.anyone_home
    to: 'on'
    id: anyone_home
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - weekday
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id:
        - weekend
      - condition: time
        weekday:
        - sun
        - sat
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
    - condition: trigger
      id:
      - anyone_home
  action:
  - service: light.turn_on
    metadata: {}
    data:
      transition: 300
    target:
      entity_id:
      - light.erik
      - light.stove
      - light.vulkan
      - light.phil
      - light.magnify
      - light.rope
      - light.trish
  - if:
    - condition: trigger
      id:
      - weekday
      - weekend
    then:
    - service: switch.turn_on
      data: {}
      target:
        device_id: c0618f784cee97f4afa59272c6191a7f
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: 4037ad983afd4ce0ad5c6bc6b252c74e
      type: set_position
      position: 10
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: 6ffaf38c7847023443155190bfcae42d
      type: set_position
      position: 50
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: a19ec029d8766f0bab706de9debcff59
      type: set_position
      position: 80
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 65
  - if:
    - condition: trigger
      id:
      - anyone_home
    then:
    - service: climate.set_temperature
      metadata: {}
      data:
        temperature: 65
        hvac_mode: heat
      target:
        entity_id: climate.heater_pid_climate_controller
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 5
    target:
      entity_id: light.desk
  mode: single
- id: '1707931473124'
  alias: Bye
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
    id: sleepy_time
  - platform: state
    entity_id:
    - input_boolean.anyone_home
    id: anyone_home
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: c0618f784cee97f4afa59272c6191a7f
  - if:
    - condition: trigger
      id:
      - sleepy_time
    then:
    - service: switch.turn_on
      metadata: {}
      data: {}
      target:
        device_id:
        - 7b043f943364cacf3c00827a7355653f
        - b0b04e316bb241bc98be3a12aac77931
    - service: climate.set_temperature
      metadata: {}
      data:
        temperature: 62
      target:
        entity_id: climate.heater_pid_climate_controller
    - service: light.turn_off
      metadata: {}
      data:
        transition: 120
      target:
        area_id:
        - bathroom
        - entry
        - kitchen
        - studio
        - closet
  - if:
    - condition: trigger
      id:
      - anyone_home
    then:
    - service: climate.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: climate.heater_pid_climate_controller
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id:
      - bathroom
      - closet
      - entry
      - kitchen
      - studio
  mode: single
- id: '1708445717490'
  alias: KMotion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 596935b8e44dd98e99b020ec4685e78d
    entity_id: 716c20000acf1fe8d580c9a0cfa9304b
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  - if:
    - condition: device
      device_id: a45bdc9cf829957cdd6468addcd07951
      domain: media_player
      entity_id: 764a9c64330d5e4a5de3a2ede225da1a
      type: is_playing
    then:
    - service: media_player.media_pause
      metadata: {}
      data: {}
      target:
        entity_id: media_player.prong
  - if:
    - condition: sun
      before: sunset
      after: sunrise
    then:
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 50
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 596935b8e44dd98e99b020ec4685e78d
      entity_id: 716c20000acf1fe8d580c9a0cfa9304b
      domain: binary_sensor
    continue_on_timeout: false
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  - if:
    - condition: sun
      before: sunset
      after: sunrise
    then:
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 70
  mode: restart
- id: '1708446778653'
  alias: Brrrr
  description: ''
  trigger:
  - platform: time
    at: 04:00:00
  condition:
  - condition: state
    entity_id: input_boolean.anyone_home
    state: 'on'
  action:
  - service: climate.set_temperature
    metadata: {}
    data:
      hvac_mode: heat
      temperature: 68
    target:
      entity_id: climate.heater_pid_climate_controller
  mode: single
- id: '1709535186772'
  alias: TV Dim Mode
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.12
    target:
      entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'off'
    then:
    - service: script.tv_sleep_mode
      metadata: {}
      data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - service: script.dark_mode
      metadata: {}
      data: {}
  mode: single
- id: '1709535417856'
  alias: TV Bright Mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.prong
    from: standby
    to: paused
  - platform: state
    entity_id:
    - media_player.prong
    from: standby
    to: idle
  condition:
  - condition: sun
    before: sunset
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - service: script.dark_mode
      metadata: {}
      data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'on'
    then:
    - service: script.tv_sleep_mode
      metadata: {}
      data: {}
  mode: single
- id: '1709574568785'
  alias: TV Light Sensitivity
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1:15:00'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: media_player.prong
      state: playing
    then:
    - service: media_player.volume_set
      metadata: {}
      data:
        volume_level: 0.26
      target:
        entity_id: media_player.samsung
    - if:
      - condition: state
        entity_id: input_boolean.light_sensitivity
        state: 'off'
      then:
      - service: script.dark_mode
        metadata: {}
        data: {}
  mode: single
- id: '1715782988642'
  alias: TV Quiet Mode
  description: ''
  trigger:
  - platform: time
    at: '23:59:00'
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.05
    target:
      entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'off'
    then:
    - service: script.tv_sleep_mode
      metadata: {}
      data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - service: script.dark_mode
      metadata: {}
      data: {}
  mode: single
- id: '1715783114636'
  alias: Turn Off TV
  description: ''
  trigger:
  - platform: time
    at: 01:15:00
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.prong
      - media_player.samsung
    data: {}
  mode: single
