- id: '1707927514356'
  alias: BMotion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bathroom_motion
      light_target:
        entity_id: light.bathroom
- id: '1707927634977'
  alias: Emotion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.entry_motion
      light_target:
        entity_id: light.entry
      no_motion_wait: 60
- id: '1707930534922'
  alias: Onward!
  description: ''
  triggers:
  - at: 06:15:00
    id: weekday
    trigger: time
  - at: 08:00:00
    id: weekend
    trigger: time
    enabled: false
  - type: motion
    device_id: 596935b8e44dd98e99b020ec4685e78d
    entity_id: 716c20000acf1fe8d580c9a0cfa9304b
    domain: binary_sensor
    trigger: device
    id: weekend
  - type: motion
    device_id: 23b3403079b16de7bdcc83986a81dfc6
    entity_id: 423b05ce85363603c39d0ca0515502ff
    domain: binary_sensor
    trigger: device
    id: weekend
  - entity_id:
    - input_boolean.anyone_home
    to: 'on'
    id: anyone_home
    trigger: state
  conditions:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id:
        - weekday
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id:
        - weekend
      - condition: time
        weekday:
        - sun
        - sat
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
      - condition: time
        after: 08:15:00
        weekday:
        - sun
        - sat
        before: '10:00:00'
    - condition: trigger
      id:
      - anyone_home
  actions:
  - metadata: {}
    data:
      transition: 300
    target:
      entity_id:
      - light.erik
      - light.stove
      - light.vulkan
      - light.phil
      - light.magnify
      - light.rope
      - light.trish
    action: light.turn_on
  - if:
    - condition: trigger
      id:
      - weekday
      - weekend
    then:
    - data: {}
      target:
        device_id: c0618f784cee97f4afa59272c6191a7f
      action: switch.turn_on
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: 4037ad983afd4ce0ad5c6bc6b252c74e
      type: set_position
      position: 10
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: 6ffaf38c7847023443155190bfcae42d
      type: set_position
      position: 50
    - device_id: 7b043f943364cacf3c00827a7355653f
      domain: cover
      entity_id: a19ec029d8766f0bab706de9debcff59
      type: set_position
      position: 80
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 65
  - if:
    - condition: trigger
      id:
      - anyone_home
    then:
    - metadata: {}
      data:
        temperature: 65
        hvac_mode: heat
      target:
        entity_id: climate.heater_pid_climate_controller
      action: climate.set_temperature
  - metadata: {}
    data:
      brightness_pct: 5
    target:
      entity_id: light.desk
    action: light.turn_on
  mode: single
- id: '1707931473124'
  alias: Bye
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
    id: sleepy_time
  - platform: state
    entity_id:
    - input_boolean.anyone_home
    id: anyone_home
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: c0618f784cee97f4afa59272c6191a7f
  - if:
    - condition: trigger
      id:
      - sleepy_time
    then:
    - service: switch.turn_on
      metadata: {}
      data: {}
      target:
        device_id:
        - 7b043f943364cacf3c00827a7355653f
        - b0b04e316bb241bc98be3a12aac77931
    - service: climate.set_temperature
      metadata: {}
      data:
        temperature: 62
      target:
        entity_id: climate.heater_pid_climate_controller
    - service: light.turn_off
      metadata: {}
      data:
        transition: 120
      target:
        area_id:
        - bathroom
        - entry
        - kitchen
        - studio
        - closet
  - if:
    - condition: trigger
      id:
      - anyone_home
    then:
    - service: climate.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: climate.heater_pid_climate_controller
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id:
      - bathroom
      - closet
      - entry
      - kitchen
      - studio
  mode: single
- id: '1708445717490'
  alias: KMotion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 596935b8e44dd98e99b020ec4685e78d
    entity_id: 716c20000acf1fe8d580c9a0cfa9304b
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  - if:
    - condition: device
      device_id: a45bdc9cf829957cdd6468addcd07951
      domain: media_player
      entity_id: 764a9c64330d5e4a5de3a2ede225da1a
      type: is_playing
    then:
    - service: media_player.media_pause
      metadata: {}
      data: {}
      target:
        entity_id: media_player.prong
  - if:
    - condition: sun
      before: sunset
      after: sunrise
    then:
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 50
  - wait_for_trigger:
    - type: no_motion
      platform: device
      device_id: 596935b8e44dd98e99b020ec4685e78d
      entity_id: 716c20000acf1fe8d580c9a0cfa9304b
      domain: binary_sensor
    continue_on_timeout: false
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  - if:
    - condition: sun
      before: sunset
      after: sunrise
    then:
    - device_id: b0b04e316bb241bc98be3a12aac77931
      domain: cover
      entity_id: c6a4e14673af501c152d5ee0bdd54580
      type: set_position
      position: 70
  mode: restart
- id: '1708446778653'
  alias: Brrrr
  description: ''
  trigger:
  - platform: time
    at: 04:00:00
  condition:
  - condition: state
    entity_id: input_boolean.anyone_home
    state: 'on'
  action:
  - service: climate.set_temperature
    metadata: {}
    data:
      hvac_mode: heat
      temperature: 68
    target:
      entity_id: climate.heater_pid_climate_controller
  mode: single
- id: '1709535186772'
  alias: TV Dim Mode
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - if:
    - condition: numeric_state
      entity_id: media_player.samsung
      attribute: volume_level
      above: 0.12
    then:
    - action: media_player.volume_set
      metadata: {}
      data:
        volume_level: 0.12
      target:
        entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'off'
    then:
    - metadata: {}
      data: {}
      action: script.tv_sleep_mode
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - metadata: {}
      data: {}
      action: script.dark_mode
  mode: single
- id: '1709535417856'
  alias: TV Bright Mode
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.prong
    from: standby
    to: paused
  - platform: state
    entity_id:
    - media_player.prong
    from: standby
    to: idle
  condition:
  - condition: sun
    before: sunset
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - service: script.dark_mode
      metadata: {}
      data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'on'
    then:
    - service: script.tv_sleep_mode
      metadata: {}
      data: {}
  mode: single
- id: '1709574568785'
  alias: TV Light Sensitivity
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '1:15:00'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: media_player.prong
      state: playing
    then:
    - if:
      - condition: numeric_state
        entity_id: media_player.samsung
        attribute: volume_level
        above: 0.26
      then:
      - action: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.26
        target:
          entity_id: media_player.samsung
    - if:
      - condition: state
        entity_id: input_boolean.light_sensitivity
        state: 'off'
      then:
      - metadata: {}
        data: {}
        action: script.dark_mode
  mode: single
- id: '1715782988642'
  alias: TV Quiet Mode
  description: ''
  trigger:
  - platform: time
    at: '23:59:00'
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - if:
    - condition: numeric_state
      entity_id: media_player.samsung
      attribute: volume_level
      above: 0.05
    then:
    - action: media_player.volume_set
      metadata: {}
      data:
        volume_level: 0.05
      target:
        entity_id: media_player.samsung
  - if:
    - condition: state
      entity_id: input_boolean.white_point
      state: 'off'
    then:
    - metadata: {}
      data: {}
      action: script.tv_sleep_mode
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 750
  - if:
    - condition: state
      entity_id: input_boolean.light_sensitivity
      state: 'on'
    then:
    - metadata: {}
      data: {}
      action: script.dark_mode
  mode: single
- id: '1715783114636'
  alias: Turn Off TV
  description: ''
  trigger:
  - platform: time
    at: 01:15:00
  condition:
  - condition: state
    entity_id: media_player.prong
    state: playing
  action:
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.prong
      - media_player.samsung
    data: {}
  mode: single
- id: '1728014433536'
  alias: Bench
  description: Let's Solder!
  triggers:
  - device_id: 62e6f83f8d10df332c77c6238e3abb09
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: 'on'
  - device_id: 62e6f83f8d10df332c77c6238e3abb09
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
    id: 'off'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - action: adaptive_lighting.set_manual_control
      metadata: {}
      data:
        manual_control: true
        entity_id: switch.adaptive_lighting_adapt_brightness_main
        lights:
        - light.magnify
        - light.soldering_light
        - light.trish
    - action: fan.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: fan.soldering_fan
    - action: light.turn_on
      metadata: {}
      data:
        brightness_pct: 100
      target:
        entity_id:
        - light.soldering_light
        - light.magnify
        - light.trish
  - if:
    - condition: trigger
      id:
      - 'off'
    then:
    - action: adaptive_lighting.set_manual_control
      metadata: {}
      data:
        manual_control: false
        entity_id: switch.adaptive_lighting_adapt_brightness_main
        lights:
        - light.magnify
        - light.soldering_light
        - light.trish
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.soldering_light
    - action: fan.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: fan.soldering_fan
  mode: single
- id: '1728020947954'
  alias: Work Lights
  description: ''
  triggers:
  - type: motion
    device_id: 97114d7e6ec7d418df899849ba92c756
    entity_id: fd3cbcbfc5bc5355af4a542c90471ea4
    domain: binary_sensor
    trigger: device
    id: 'on'
  - type: no_motion
    device_id: 97114d7e6ec7d418df899849ba92c756
    entity_id: fd3cbcbfc5bc5355af4a542c90471ea4
    domain: binary_sensor
    trigger: device
    id: 'off'
  conditions:
  - condition: time
    before: '22:30:00'
    after: 06:00:00
  actions:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - action: adaptive_lighting.set_manual_control
      metadata: {}
      data:
        manual_control: true
        entity_id: switch.adaptive_lighting_adapt_brightness_main
        lights:
        - light.magnify
        - light.trish
    - action: light.turn_on
      metadata: {}
      data:
        brightness_pct: 80
      target:
        entity_id:
        - light.trish
        - light.magnify
    - if:
      - condition: sun
        after: sunrise
        before: sunset
        after_offset: '2: 00:00'
      then:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: 50
        target:
          entity_id:
          - cover.blinds02_left
          - cover.blinds02_center
          - cover.blinds02_right
  - if:
    - condition: trigger
      id:
      - 'off'
    then:
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - action: adaptive_lighting.set_manual_control
      metadata: {}
      data:
        manual_control: false
        entity_id: switch.adaptive_lighting_adapt_brightness_main
        lights:
        - light.magnify
        - light.trish
    - action: light.turn_on
      metadata: {}
      data: {}
      target:
        entity_id:
        - light.trish
        - light.magnify
    - if:
      - condition: sun
        before: sunset
        after: sunrise
        after_offset: '2:00:00'
      then:
      - action: cover.set_cover_position
        metadata: {}
        data:
          position: 80
        target:
          entity_id:
          - cover.blinds02_left
          - cover.blinds02_center
  mode: restart
