# From https://github.com/athom-tech/athom-configs/blob/main/athom-rgb-light.yaml

substitutions:
  light_restore_mode: RESTORE_DEFAULT_OFF

logger:
  baud_rate: 0

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - ${button_action}.toggle: "${button_target}"
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

output:
  - platform: esp8266_pwm
    id: cw_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: ww_output
    pin: GPIO4

light:
  - platform: cwww
    id: led
    restore_mode: ${light_restore_mode}
    name: "Soldering Fan Lights"
    cold_white: cw_output
    warm_white: ww_output
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset
  - platform: safe_mode
    name: "Safe Mode"
    internal: false

     
time:
  - platform: sntp
    id: sntp_time