substitutions:
  name: "walllight"
  friendly_name: "Display Wall Light"
  board: esp8285
  sensor_update_interval: 10s

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athom5050c: !include .athom-5050.yaml

# wifi:
#   use_address: test8266.local