# From https://github.com/athom-tech/athom-configs/blob/main/athom-rgb-light.yaml

logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-rgb-light.yaml

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: led
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset
  - platform: safe_mode
    name: "Safe Mode"
    internal: false

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14

light:
  - platform: rgb
    name: "RGB Light Strip"
    restore_mode: RESTORE_DEFAULT_OFF
    red: red_output
    green: green_output
    blue: blue_output
    id: led
     
time:
  - platform: sntp
    id: sntp_time