# From https://github.com/athom-tech/athom-configs/blob/main/athom-rgbw-light.yaml
# For high power strip controller

substitutions:
  # device_name: "athom-rgbw-light"
  project_name: "Athom Technology.RGBW Light Strip Controller"
  project_version: "1.1"
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  # name: "${device_name}"
  # friendly_name: ""
  # name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

# esp8266:
#   board: esp8285
#   restore_from_flash: true

# api:

# ota:

logger:
  baud_rate: 0

# mdns:
#   disabled: false

# web_server:
#   port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-rgbw-light.yaml

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: leds
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4

  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12

  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14

  - platform: esp8266_pwm
    id: output_white
    pin: GPIO13

light:
  - platform: rgbw
    name: "RGBW_Controller"
    id: leds
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: true


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "Mac Address"
     
time:
  - platform: sntp
    id: sntp_time