# Top level settings
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32: 
  board: ${board}
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# This didn't seem to work for the xiao camera
# sensor:
#   - platform: internal_temperature
#     name: "Internal Temperature"
