substitutions:
  name: "maslow"
  friendly_name: "Maslow Light"
  board: esp8285
  sensor_update_interval: 10s

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athomrgbw-light: !include .athom-light-rgbw.yaml

# wifi:
#   use_address: athom-smart-plug-v2-9d92a2.local