substitutions:
  name: "pedestallight"
  friendly_name: "Pedestal Lamp"
  board: esp8285
  sensor_update_interval: 10s
  project_name: "Athom Technology.RGBCW Bulb"
  project_version: "1.1"

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athomrgbww-light: !include .athom-light-rgbww.yaml

# wifi:
#   use_address: athom-smart-plug-v2-9d92a2.local