substitutions:
  name: "rhooutlet"
  friendly_name: "Rho Outlet"
  # device_name: "athom-rgb-light"
  board: esp8285
  sensor_update_interval: 10s

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athomoutlet: !include .athom-outlet.yaml

# wifi:
#   use_address: test8266.local