substitutions:
  name: "rholight"
  friendly_name: "Rho Light"
  board: esp8285
  num_leds: '9'
  neopixel_type: GRB
  led_chipset: WS2811

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athomws2812b-light: !include .athom-light-ws2812b.yaml
  