substitutions:
  name: "siglight"
  friendly_name: "Sigma Light"
  board: esp8285
  num_leds: '1'
  neopixel_type: GRB
  led_chipset: WS2811

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athows2812b-light: !include .athom-light-ws2812b.yaml
