substitutions:
  name: "willwalllight"
  friendly_name: "Will Wall Light"
  board: esp8285
  sensor_update_interval: 10s
  button_action: "light"
  button_target: led

packages:
  # board/wifi/ota stuff
  common: !include .common.yaml
  esp8266: !include .esp8266.yaml
  athomrgb-light: !include .athom-light-rgb.yaml


